#!/bin/sh

( printf -- '-Version\n\n'
  ( ip help
    ip link help ) 2>&1 |
   sed -ne '
            /OBJECT *:= *{/,/}/ bq;
            /TYPE *:= *{/,/}/bl;

            d;

            :l;
            s/[{|] */&link set type /g;

            :q;
            s/.*:= *{ *//;
            s/ *} *$//;

            s/| */\n/g;

            s/  */ /g;
            s/^ //;
            s/ $//;
            p;
        ' |
    sort -u
) |

while read t
do  printf '%s\n\n' "$t"
    ip $t help
    printf '\n################################\n'
done 2>&1 |

sed -e '
        /{/ {
            :a;
            /{[^}]*$/ {
                N;
                ba;
            }
            s/\n */ /g;
        }'


exit
    -e '
            s/   */ /g;
            h;
            s/\({[^{}]*[^ }]\) *|.*/\1/;
            Tx;
            p;
            g;
            s/ *{ *[^{}]*|/ { /;
            tr;
            :r;
            s/[^ ]\( *{\)/ \1/;
            tr;
            s/[{]/|/;
            to;

            :o;
            h;
            s/|\([^{}]*[^ }]\) *|.*/| \1/;
            p;
            Tx;
            g;
            s/|[^{}|]*}/|/;
            to;

            :x;
            n;
        }
    '
