#!/bin/bash
#
# To enable this hook, copy or link this file to ".git/hooks/pre-commit".

# Normally diff against head ...
export git_head=HEAD
# ... but for an initial commit, diff against an empty tree object
git rev-parse --verify "$git_head" >/dev/null 2>&1 && git_head=4b825dc642cb6eb9a060e54bf8d69288fbee4904

if [[ -d .git.precommit.d ]]
then
    for f in .git.precommit.d/[0-9]*[0-9a-zA-Z]
    do
        "$f" || { r=$? ; printf 'git pre-commit check %s failed.\n' "$f" ; exit $r ; }
    done
fi
